### ISSUE TITLE
Import module looking in wrong location for Logger package

### ISSUE THREAD

**Issue by Issue3996** [alexasterisk/WallyPackages#5]
Issue locations is Line 1 of Import init, L11 Import dirs, auto requiring logger is trying to look in _Index for package script, needs to be looking one parent lower.

```
--import.lua line 1
local logger = require(script.Parent.Parent.Logger) "import"

--dirs.lua line 11
local logger = require(script.Parent.Parent.Parent.Logger) "import"
```

should be 
 
```
--import.lua line 1
local logger = require(script.Parent.Logger) "import"

--dirs.lua line 11
local logger = require(script.Parent.Parent.Logger) "import"
```

Output: 
![image](https://github.com/alexasterisk/WallyPackages/assets/29945730/8d122d98-1dab-43aa-bdfa-4d5d61cdd2d6)

File structure:
![image](https://github.com/alexasterisk/WallyPackages/assets/29945730/bb0b200a-c05e-4500-bc2e-fbbd4e9ac93c)

**Comment by alexasterisk** [comment]
This is interesting, was Wally updated? I don't remember it adding dependency references directly into the main file. Thanks for letting me know!

**Comment by alexasterisk** [comment]
I have looked into this and have fixed this issue in **Import** `v0.1.9`
Please tell me if there's anything else you run into! Also feel free to open pull requests too! Thank you for your help.

**Comment by Issue3996** [comment]
Not at home at the moment so can’t check the Wally version for you sorry, but issue is resolved. Cheers 🤙🏽

**Comment by alexasterisk** [comment]
Of course! Let me know if you run into anything else. I have been planning on making Import more optimized at some point™️ but nothing on the board yet. When a change is made, expect it to be compatible with your current setup though!
